direction: right

developer: Developer

ec2: AWS EC2 {
  server: NestJS Server
}

github: Github {
  shape: image
  icon: https://icons.terrastruct.com/dev%2Fgithub.svg
}

github actions: Github Actions

developer -> github: git push
github -> github actions: trigger
github actions -> ec2.Server: Deploy
